#!/bin/bash

clear

RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

ART="${RED}
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡿⠟⠉⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠉⠻⣿⣿⣿⣿⣿⣿
⣿⣿⣿⠿⠋⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠄⠄⠄⠄⠙⢿⣿⣿⣿
⣿⡟⠁⠄⠄⠄⠄⠄⠄⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠁⠄⠄⠄⠄⠄⠄⠙⢿⣿
⣿⣷⣿⣶⣤⡀⠄⠄⠄⠄⠈⠿⣿⣿⢹⡟⣿⣿⠟⠄⠄⠄⠄⠄⣀⣤⣾⣿⣾⣿
⣿⣿⣿⣿⣿⣿⡆⠄⠄⠄⠄⠄⠙⠟⠘⠃⡿⠁⠄⠄⠄⠄⠄⢸⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣷⣀⣀⡀⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣀⣀⣀⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⠄⠄⠄⠄⠄⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠄⠄⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣿⣿⣿⣿
ID RUBIKA:@bardii93
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
${NC}"

show_menu() {
    echo -e "${ART}"
    echo -e "${YELLOW}                                    ....error${NC}"
    echo ""
    echo -e "${GREEN}   1 Coobe Fil${NC}"
    echo -e "${RED}   2 Exit${NC}"
    echo ""
    echo -e "${CYAN}  BARDIA🕷️🕷️🕷️🕷️🕷️🕷️🕷️: ${NC}"
}

LINKS=(
    "http://v.3.0.2.yftt15k.in"
    "http://sex.report.offline.online.in"
    "http://report.com"
    "http://xXx.co"
    "http://server.3.5.7.yfttk08.in"
    "http://yfttk17.in"
    "https://fa.m.wikipedia.org/wiki/%D8%B3%DB%8C%D8%AF_%D8%B1%D9%88%D8%AD%E2%80%8C%D8%A7%D9%84%D9%84%D9%87_%D8%AE%D9%85%DB%8C%D9%86%DB%8C"
    "http://ffmodmenu.page.link/Anti-V")

while true; do
    clear
    show_menu
    read -r choice

    case $choice in
        1)
            clear
            echo -e "${RED}"

            DIR_NAME="code_filter"
            FILE_NAME="links_output.txt"

            mkdir -p "$DIR_NAME"

            printf "%s\n" "${LINKS[@]}" > "$DIR_NAME/$FILE_NAME"

            echo -e "${GREEN}[✓] Links saved to $DIR_NAME/$FILE_NAME${NC}"
            echo ""
            echo -e "${YELLOW}To view the file, run:${NC}"
            echo -e "${CYAN}   cd $DIR_NAME && ls && cat $FILE_NAME${NC}"
            echo ""
            echo -e "${NC}"
            echo ""
            echo -e "${YELLOW} Press Enter to exit...${NC}"
            read -r
            ;;
        2)
            clear
            echo -e "${GREEN}   Exited.${NC}"
            exit 0
            ;;
        *)
            echo -e "${RED}   Invalid option! Press Enter and try again.${NC}"
            read -r
            ;;
    esac
done
